# Generated by Django 6.1.1 on 2026-09-24 18:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('logo_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='PartCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='cars.carbrand')),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('description', models.TextField()),
                ('model_url', models.URLField()),
                ('image_url', models.URLField()),
                ('car_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='cars.carmodel')),
            ],
        ),
        migrations.CreateModel(
            name='CarPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('component_id', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('function', models.TextField()),
                ('image_url', models.URLField()),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='cars.car')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_parts', to='cars.partcategory')),
            ],
        ),
        migrations.CreateModel(
            name='PartSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('url', models.URLField()),
                ('car_part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='cars.carpart')),
            ],
        ),
        migrations.CreateModel(
            name='PartSpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=255)),
                ('car_part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specifications', to='cars.carpart')),
            ],
        ),
        migrations.CreateModel(
            name='RelatedCarPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_part_links', to='cars.carpart')),
                ('related_part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_related_part_links', to='cars.carpart')),
            ],
        ),
        migrations.AddConstraint(
            model_name='carpart',
            constraint=models.UniqueConstraint(fields=('car', 'component_id'), name='unique_car_component_id'),
        ),
    ]
